name: Docker Build and Push to DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  prepare_environment:
    name: Prepare Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build_builder_stage:
    name: Build and Push Builder Stage
    needs: prepare_environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build Builder Stage
        run: |
          docker build \
            --target builder \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder .

      - name: Push Builder Stage
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder

  build_and_push_final_stage:
    name: Build and Push Final Stage
    needs: build_builder_stage
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp for Docker tags
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Final Stage
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder,mode=max
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:${{ env.TIMESTAMP }}
