name: Docker Build and Push to DockerHub

on:
  push:
    branches:
      - main


permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build_and_test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull builder cache from DockerHub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder || true

      - name: Build builder stage
        run: |
          docker build \
            --target builder \
            --cache-from ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder \
            --tag builder:latest .

  build_and_push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull cache from DockerHub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:latest || true

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:builder,mode=max
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pythonpagertelegramforwarder:$(date +%Y%m%d%H%M%S)
